### ISSUE TITLE
Where to put a project description?

### ISSUE THREAD

**Issue by CGRBZH** [statistikZH/STAT_Template#2]
One part of a README should be a project description. This is where I would look for instructions on evaluations, calculations or descriptions and codings of variables or things to pay attention to when running the code.

The section Use this Project may be the appropriate place for this. However, at the moment it seems to me to be more of a place to provide citation suggestions.

**Comment by mmznrSTAT** [comment]
Ich würde die Projektbeschreibung  gleich nach Projekttitel nehmen.
